server:
  port: 8080

spring:
  application:
    name: telemetry-collector

collector:
  grpc:
    port: 59091
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1

grpc:
  server:
    port: 59091
