spring:
  application:
    name: shopping-cart
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
      fail-fast: false
      request-connect-timeout: 1000
      request-read-timeout: 1000
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: commerce
    password: commerce
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  circuitbreaker:
    enabled: true
