server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_store
    username: shopping_store
    password: shopping_store
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
