spring:
  application:
    name: analyzer
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      hub-group-id: telemetry-analyzer-hub
      snapshot-group-id: telemetry-analyzer-snapshot
    topics:
      hubs: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1

grpc:
  server:
    port: -1
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
